### ISSUE TITLE
[Error] Subscribing to channels error

### ISSUE THREAD

**Issue by cursedmantra** [lighttube-org/LightTube#150]
### Describe what happened

Trying to subscribe to any channel **OFTEN** returns an error screen.

### Instance URL

https://tube.kuylar.dev

### LightTube & InnerTube versions

v2024.4.13 / 1.0.29.0

### Resource path

(/channel/UC1wUo-29zS7m_Jp-U_xYcFQ/subscription)

### Language & region

en_AR

### Stack trace

```
 System.NullReferenceException: Object reference not set to an instance of an object.
at LightTube.Database.Models.DatabaseChannel..ctor(InnerTubeChannelResponse channel) in /src/LightTube/Database/Models/DatabaseChannel.cs:line 18
at LightTube.Controllers.YoutubeController.Subscription(String id) in /src/LightTube/Controllers/YoutubeController.cs:line 199
``` 

### Notes

* I say "often" in the description because it occasionally does work correctly, but it will display the error anyways so it's difficult to tell whether it worked or not.

**Comment by cursedmantra** [comment]
* A temporary solution seems to be just retrying until it works.
