### ISSUE TITLE
[Bug] error searching for video

### ISSUE THREAD

**Issue by atomGit** [lighttube-org/LightTube#166]
### Describe the bug

i've run into this error more often than not when searching for content - the LT instance doesn't seem to matter

    LightTube instance this error occured on (tube.instellate.xyz)
    LightTube & InnerTube versions (2024.8.15 / 2.0.0.18)
    The full resource path (/results?search_query=yaesu+radioddity+cb)
    InnerTube language & region (en_JP)

```
System.InvalidCastException: Unable to cast object of type 'InnerTube.Renderers.UnknownRendererData' to type 'InnerTube.Renderers.VideoRendererData'.
at AspNetCoreGeneratedDocument.Views_Shared_Renderers_ContainerRenderer.ExecuteAsync() in /src/LightTube/Views/Shared/Renderers/ContainerRenderer.cshtml:line 208
at AspNetCoreGeneratedDocument.Views_Shared_Renderers_SearchRenderer.ExecuteAsync() in /src/LightTube/Views/Shared/Renderers/SearchRenderer.cshtml:line 151
at AspNetCoreGeneratedDocument.Views_Youtube_Search.ExecuteAsync() in /src/LightTube/Views/Youtube/Search.cshtml:line 453
--- End of stack trace from previous location --- 
```

**Comment by kevinfiol** [comment]
Also seeing this. Seems to happen on the official instance as well.

**Comment by kuylar** [comment]
Looks like YouTube replaced the renderer used for short videos with "`shortsLockupViewModel`", which LightTube doesn't expect. Moving to (InnerTube)[https://github.com/lighttube-org/InnerTube] since it's an extractor issue
